import os

GITHUB_PERSONAL_ACCESS_TOKEN = os.getenv('GITHUB_PERSONAL_ACCESS_TOKEN')

TWITTER_API_KEY = os.getenv('TWITTER_API_KEY')
TWITTER_KEY_SECRET = os.getenv('TWITTER_KEY_SECRET')
TWITTER_BEARER_TOKEN = os.getenv('TWITTER_BEARER_TOKEN')
